### ISSUE TITLE
Build process does not stop when the electron window is closed

### ISSUE THREAD

**Issue by cawa-93** [ci010/electron-vue-next#13]
I faced a strange problem.
If you run the `npm run dev` command and then close the electron window yourself, the build process does not stop and you have to kill it with `CTRL+C`.

In my experience, this is expected behavior.

I did a little research and it looks like the rollup watcher keeps watching the changes in the `main` files.

I'm not sure if this is a planned behavior. Just in case, [this patch](https://github.com/cawa-93/electron-vue-next/commit/0b6f4ca472b1eb6774ec8be12a48ac050e7504d5) fixed the problem for me. Although I'm not sure if this is the best solution.

**Comment by ci010** [comment]
Yes, in original electron-vue, once the app close, all the dev servers are closed.
Personally, I feel neutral this behavior, but I guess more people think the dev server should be quit after app closed. I'm glad to receive that patch 😄 .
