### ISSUE TITLE
Usage of optionalDependencies

### ISSUE THREAD

**Issue by ci010** [ci010/electron-vue-next#26]
@cawa-93 It seems `npm install` will add the `optionalDependencies` into the `dependencies` list. I think maybe we should just keep the eslint in the `devDependencies`

**Comment by cawa-93** [comment]
@ci010 Thus, by default, optional dependencies are install in the same way as `devDependencies`. The same under normal conditions, the difference is not noticeable. However, the idea is to be able to skip the installation of dependencies that are not required for compilation. This will, though not significantly, reduce `build` time. Lets say why we need install `eslint` and all eslint plugins if only `build:production` will be run?

**Comment by ci010** [comment]
I understand your concern. I agree with the idea that, lesser the dependencies we have, shorter the build time will take.

My point is this might confuse user. For example,

If someone try to run `npm install` locally and install the dependencies (maybe they just clone the project).
The `npm` will install all dependencies and modify the local `package.json`, adding all `optionalDependencies` into `dependencies`. If user doesn't notice that, the `npm run dev` will failed as some eslint dependencies are using node modules.

In the case I described above, there are two unexpected things:

1. npm will modify the package.json, adding eslint packages to `dependencies`.
2. vite will fail if user does not move the eslint package to `devDependencies`.

**Comment by cawa-93** [comment]
> npm will modify the package.json, adding eslint packages to dependencies.

I do not observe this problem. I just did some tests in the master. After `npm install` eslint remains in `optionalDependencies`.

Windows
npm version: 6.14.8

**Comment by ci010** [comment]
> > npm will modify the package.json, adding eslint packages to dependencies.
> 
> I do not observe this problem. I just did some tests in the master. After `npm install` eslint remains in `optionalDependencies`.
> 
> Windows
> npm version: 6.14.8

ah, I'm using the npm 7.0.3. I'm not sure if this is a bug of the npm 7.

**Comment by cawa-93** [comment]
https://github.com/npm/cli/issues/1886

**Comment by ci010** [comment]
Close due to the new project structure.
