### ISSUE TITLE
How to use electron-updater

### ISSUE THREAD

**Issue by ghost-void** [ci010/electron-vue-next#30]
If import electron-updater in src/main/index.ts, build failed.
if require('electron-updater')  in src/main/index.ts, it will crash when app startup, says thant can not find module electron-updater.

**Comment by ci010** [comment]
It seems my rollup config has some problem. I'm currently working on the fix...

**Comment by ci010** [comment]
I think I fix the issue of using the external packages like `electron-updater`. You can try it again.
