### ISSUE TITLE
support JSX & TSX ?

### ISSUE THREAD

**Issue by UncleCarlos** [ci010/electron-vue-next#38]
I'm a newcomer and I don't understand Electron at all, I just started to pay attention to it recently.
I can hardly understand the code in your `scripts` directory.

I am making a practice project that mock the VSCode interface based on your repo, in order to learn vue3(tsx) and vite.

How can support JSX and TSX? thanks.

chinese?

**Comment by cawa-93** [comment]
It must work out-of-box
See https://github.com/vitejs/vite#jsx

**Comment by UncleCarlos** [comment]
ok. thanks for reply.
