### ISSUE TITLE
service:call multiple parameters

### ISSUE THREAD

**Issue by cyber-carlos** [ci010/electron-vue-next#39]
https://github.com/ci010/electron-vue-next/blob/d85735fb9a64a3dbbf36232b3280a4efff69f197/src/renderer/hooks/service.ts#L9-L10

```typescript
      return (...payload: any) => {
        return invoke('service:call', service, functionName as string, ...payload)
```

https://github.com/ci010/electron-vue-next/blob/d85735fb9a64a3dbbf36232b3280a4efff69f197/src/main/services/index.ts#L77

```typescript
        return service[method](...args)
```

when service:call passes multiple parameters, I think it can be changed like this.

```typescript
const { fetchConfig } = useService('RedisService')
const dbCount= ref(0)

onMounted(async ()=> {
  const result = await fetchConfig(client, 'get', 'databases')
  dbCount.value = result[1]
}
```
```console
[console] [ 'e4a95375-7555-4e53-9eac-c2ceb3e066d4', 'get', 'databases' ]
```

**Comment by ci010** [comment]
Yes, I think it will be good to support the multi-params. Since in my old project, the services are used to be the vuex actions, it keeps the vuex design that only pass one param. This will fix in next patch. Thanks the feedback!

**Comment by ci010** [comment]
This should be supported in https://github.com/ci010/electron-vue-next/commit/98d0d44da04fa2d9702994f7f1904684b3bb40c7
