### ISSUE TITLE
打开应用报错

### ISSUE THREAD

**Issue by chengaomin** [ci010/electron-vue-next#42]
npm run build:production 之后，build成功，但是打开应用，空白页，报错如下

![image](https://user-images.githubusercontent.com/4586906/107777592-fee9b200-6d7d-11eb-8981-0ddeeecc9460.png)

![image](https://user-images.githubusercontent.com/4586906/107777625-0f019180-6d7e-11eb-9df4-f9e1e31827dd.png)

**Comment by ci010** [comment]
应该是bug，我康康
