### ISSUE TITLE
Empty windows loaded in production mode

### ISSUE THREAD

**Issue by mohannad-musleh** [ci010/electron-vue-next#45]
The main and side windows open with empty content in production

Enviroment:
- OS: Linuxmint x64
- node version: v14.15.1
- npm version: 7.6.3

Reproduce steps:
- create a new project using `npm init electron-vue-next <app-dirname>`
- navigate to project directory
- run `npm install`
- update the `scripts/build.config.js`
  - remove all linux build targets except `AppImage`
- run `npm run build:production`
![console](https://user-images.githubusercontent.com/7196034/111021895-0c737580-83d8-11eb-9667-08fdaada2fb6.png)
- run the application (AppImage): `./build/vite-electron-example-2-0.0.0.AppImage`
![image](https://user-images.githubusercontent.com/7196034/111021932-4cd2f380-83d8-11eb-8555-fe44704470e2.png)

notes:
- i tried to disable the asar, but the problem not fixed
- i tired to run the application from linux-unpacked (`./build/linux-unpacked/vite-electron-example-2 `), also the issue not fixed

**Comment by ci010** [comment]
Sorry about the late reply. I don't have a Linux machine for now. (I'll setup a vm but it takes time)

Can you try to open the Developer Tool for both windows and see if there is any error?

And you didn't mention in the post, but I guess your `npm run dev` is working. Is it?

**Comment by ci010** [comment]
I found the root cause is the new file path url injection does not inject the path with file:// protocol. Will fix in next version. Thanks!

**Comment by mohannad-musleh** [comment]
@ci010 thank you very much!
