### ISSUE TITLE
nothing happens after yarn dev command

### ISSUE THREAD

**Issue by soulsam480** [ci010/electron-vue-next#5]
Hey, I tried to run the app, but nothing happens after hitting `yarn dev`. Plase look into this issue!!

**Comment by ci010** [comment]
I didn't try with the yarn yet, but I will check it out later.

**Comment by ci010** [comment]
I installed yarn `v1.22.10` globally, and `npx yarn dev`. It works totally fine. Did you try to re-install the dependencies?

**Comment by soulsam480** [comment]
I'm really sorry for the late reply. No, I haven't tried to reinstall dependencies. I Will try and let you know. Thanks!!
